#!/bin/bash



#Firewall
apt-get install ufw && ufw enable

#Lock root user
passwd -l root

#set up auditing
apt-get install auditd && auditctl -e 1

#Update for dependencies
apt-get install wget sed git -y

#SYSCTL.CONF
wget -q -c https://raw.githubusercontent.com/conduro/ubuntu/main/sysctl.conf -O /etc/sysctl.conf

#IP Spoofing protection
net.ipv4.conf.all.rp_filter = 1
net.ipv4.conf.default.rp_filter = 1
net.ipv4.ip_forward = 0 

# Ignore ICMP broadcast requests
net.ipv4.icmp_echo_ignore_broadcasts = 1

# Disable source packet routing
net.ipv4.conf.all.accept_source_route = 0
net.ipv6.conf.all.accept_source_route = 0 
net.ipv4.conf.default.accept_source_route = 0
net.ipv6.conf.default.accept_source_route = 0

# Ignore send redirects
net.ipv4.conf.all.send_redirects = 0
net.ipv4.conf.default.send_redirects = 0

# Block SYN attacks
net.ipv4.tcp_syncookies = 1
net.ipv4.tcp_max_syn_backlog = 2048
net.ipv4.tcp_synack_retries = 2
net.ipv4.tcp_syn_retries = 5

# Log Martians
net.ipv4.conf.all.log_martians = 1
net.ipv4.icmp_ignore_bogus_error_responses = 1

# Ignore ICMP redirects
net.ipv4.conf.all.accept_redirects = 0
net.ipv6.conf.all.accept_redirects = 0
net.ipv4.conf.default.accept_redirects = 0 
net.ipv6.conf.default.accept_redirects = 0

# Ignore Directed pings
net.ipv4.icmp_echo_ignore_all = 1

# Disable IPv6
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
net.ipv6.conf.lo.disable_ipv6 = 1

# Hide kernel pointers
kernel.kptr_restrict = 2

# Enable panic on OOM
vm.panic_on_oom = 1

# Reboot kernel ten seconds after OOM
kernel.panic = 10


#Install update
apt-get update -y && apt-get upgrade -y && apt-get dist-upgrade -y && apt-get full-upgrade -y 

#Configure automatic updates, enter:
sudo vi /etc/apt/apt.conf.d/50unattended-upgrades

#Turn on unattended security updates, run:
sudo dpkg-reconfigure -plow unattended-upgrades

#sshd_config
if grep -qF 'PermitRootLogin' /etc/ssh/sshd_config;
then sed -i 's/^.*PermitRootLogin.*$/PermitRootLogin no/' /etc/ssh/sshd_config;
else echo 'PermitRootLogin no' >> /etc/ssh/sshd_config;
fi
PermitRootLogin no
UsePAM yes
PermitEmptyPasswords no

#SSHD
wget -q -c https://raw.githubusercontent.com/conduro/ubuntu/main/sshd.conf -O /etc/ssh/sshd_config

# Block client 10 minutes after 3 failed login attempts
MaxAuthTries 3
LoginGraceTime 10

#local connections only (might need to remove only use at end)
sudo ufw allow from 202.54.1.5/29 to any port 22

#no keepalive or unattended sessions also at end?
ClientAliveInterval 900
ClientAliveCountMax 0

#disable obselete rsh settings also at end
IgnoreRhosts yes

#remove samba related
apt-get remove .*samba.* .*smb.*

#find music
find /home/ -type f \( -name "*.mp3" -o -name "*.mp4" \)

#remove hacking tools
find /home/ -type f \( -name "*.tar.gz" -o -name "*.tgz" -o -name "*.zip" -o -name "*.deb" \)

#install clamav
sudo apt-get install clamav clamav-daemon

#disable guest
echo 'allow-guest=false' >> /etc/lightdm/lightdm.conf

#check for rootkits, backdoors
sudo apt-get install chkrootkit rkhunter
sudo chkrootkit
sudo rkhunter --update
sudo rkhunter --check

#Remove Zenmap
sudo apt-get remove remove --auto-remove zenmap

echo"Remove unused systems"
sudo apt-get autoclean && sudo apt-get autoremove

#Autoupdate
    sudo add-apt-repository -y ppa:libreoffice/ppa
    sudo killall firefox
  sudo apt-get --purge --reinstall install firefox -y
    sudo apt-get install clamtk -y

    sudo apt-get update -y
  sudo apt-get upgrade -y
  sudo apt-get dist-upgrade -y


#password policy
    apt-get install libpam-cracklib || yum install libpam-cracklib
  sed -i.bak -e 's/PASS_MAX_DAYS\t[[:digit:]]\+/PASS_MAX_DAYS\t90/' /etc/login.defs
  sed -i -e 's/PASS_MIN_DAYS\t[[:digit:]]\+/PASS_MIN_DAYS\t10/' /etc/login.defs
  sed -i -e 's/PASS_WARN_AGE\t[[:digit:]]\+/PASS_WARN_AGE\t7/' /etc/login.defs
  sed -i -e 's/difok=3\+/difok=3 ucredit=-1 lcredit=-1 dcredit=-1 ocredit=-1/' /etc/pam.d/common-password



#Media files
    sudo find / -name '*.mp3' -type f -delete
    sudo find / -name '*.mov' -type f -delete
    sudo find / -name '*.mp4' -type f -delete
    sudo find / -name '*.avi' -type f -delete
    sudo find / -name '*.mpg' -type f -delete
    sudo find / -name '*.mpeg' -type f -delete
    sudo find / -name '*.flac' -type f -delete
    sudo find / -name '*.m4a' -type f -delete
    sudo find / -name '*.flv' -type f -delete
    sudo find / -name '*.ogg' -type f -delete

#No user files
find /dir -xdev \( -nouser -o -nogroup \) -print

#reload system
sysctl -p
update-grub2
systemctl restart systemd-timesyncd
ufw --force enable
service ssh restart

#check file for correctness before start
sudo sshd -t
